# Generated by Django 4.2.30 on 2026-05-15 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recommendation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="userinteraction",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="session_key",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="query",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="session_key",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userinteraction",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("view", "Viewed"),
                    ("click", "Clicked"),
                    ("cart", "Added to Cart"),
                    ("purchase", "Purchased"),
                    ("like", "Liked/Feedback"),
                    ("search", "Searched"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userinteraction",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="store.product",
            ),
        ),
        migrations.AlterField(
            model_name="userinteraction",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="userinteraction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["timestamp"], name="store_useri_timesta_56b8f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["interaction_type", "timestamp"],
                name="store_useri_interac_322066_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["user", "timestamp"], name="store_useri_user_id_22b7c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["session_key", "timestamp"],
                name="store_useri_session_60f9df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["product", "timestamp"], name="store_useri_product_a92886_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user__isnull", False),
                    ("session_key__isnull", False),
                    _connector="OR",
                ),
                name="recommendation_user_or_session_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "product"),
                name="unique_recommendation_user_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_key__isnull", False)),
                fields=("session_key", "product"),
                name="unique_recommendation_session_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="userinteraction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user__isnull", False),
                    ("session_key__isnull", False),
                    _connector="OR",
                ),
                name="interaction_user_or_session_present",
            ),
        ),
    ]
