# Generated by Django 4.2.16 on 2026-05-16 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_recommendation_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("dummyjson", "DummyJSON"),
                            ("platzi", "Platzi Fake Store"),
                            ("bestbuy", "Best Buy"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("base_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="external_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_external",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="manages_local_stock",
            field=models.BooleanField(
                default=True,
                help_text="If false, this product is sourced externally and checkout happens on partner site.",
            ),
        ),
        migrations.CreateModel(
            name="ProductSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("publish_enabled", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_count", models.PositiveIntegerField(default=0)),
                ("normalized_count", models.PositiveIntegerField(default=0)),
                ("created_external_count", models.PositiveIntegerField(default=0)),
                ("updated_external_count", models.PositiveIntegerField(default=0)),
                ("created_products_count", models.PositiveIntegerField(default=0)),
                ("updated_products_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("message", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to="store.externalsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category_name", models.CharField(blank=True, max_length=120)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("image_url", models.URLField(blank=True)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("stock", models.IntegerField(blank=True, null=True)),
                ("availability", models.CharField(blank=True, max_length=120)),
                ("product_url", models.URLField(blank=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("is_published", models.BooleanField(default=False)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_product",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_product",
                        to="store.product",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_products",
                        to="store.externalsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "external_id"],
                        name="store_exter_source__5fab85_idx",
                    ),
                    models.Index(
                        fields=["is_published"], name="store_exter_is_publ_0f067b_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="externalproduct",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"), name="unique_external_source_product"
            ),
        ),
    ]
