# Generated by Django 4.2.16 on 2026-05-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_externalsource_product_external_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalsource",
            name="key",
            field=models.CharField(
                choices=[
                    ("dummyjson", "DummyJSON"),
                    ("platzi", "Platzi Fake Store"),
                    ("bestbuy", "Best Buy"),
                    ("demo_generated", "Demo Generated (local)"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
